apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-rolling
  labels:
    app: tomcat
    role: rolling-update
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: tomcat
    role: rolling-update
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
